### ISSUE TITLE
RuntimeError: Error building extension 'rcca'

### ISSUE THREAD

**Issue by Atonements** [Huntersxsx/RaNet#1]
RuntimeError: Error building extension 'rcca'

**Comment by MinamiKotoka** [comment]
Hello, I have the same error. Have you dealt with it?

**Comment by Huntersxsx** [comment]
Sorry for replying late, I think it may be related to the environment.  I successfully run my code with pytorch1.1 and RTX 2080Ti GPUs, you can refer to https://github.com/speedinghzl/CCNet/tree/pytorch-1.1 for expected solutions.

**Comment by UX404** [comment]
Using pytorch 1.1.0 raises another error:
`Traceback (most recent call last):
  File "moment_localization/test.py", line 13, in <module>
    import datasets
  File "/storage/rqshi/RaNet/moment_localization/../lib/datasets/__init__.py", line 53, in <module>
    from datasets.activitynet import ActivityNet
  File "/storage/rqshi/RaNet/moment_localization/../lib/datasets/activitynet.py", line 17, in <module>
    class ActivityNet(data.Dataset):
  File "/storage/rqshi/RaNet/moment_localization/../lib/datasets/activitynet.py", line 19, in ActivityNet
    vocab = torchtext.vocab.pretrained_aliases["glove.6B.300d"]()
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 484, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 323, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 432, in cache
    self.itos, self.stoi, self.vectors, self.dim = torch.load(path_pt)
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torch/serialization.py", line 560, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: .vector_cache/glove.6B.300d.txt.pt is a zip archive (did you mean to use torch.jit.load()?)
`
which happens with pytorch<1.6 that loads models in a different way.
It seems that these two requirements are causing a conflict.

**Comment by UX404** [comment]
Using pytorch 1.1.0 raises another error:
```
Traceback (most recent call last):
  File "moment_localization/test.py", line 13, in <module>
    import datasets
  File "/storage/rqshi/RaNet/moment_localization/../lib/datasets/__init__.py", line 53, in <module>
    from datasets.activitynet import ActivityNet
  File "/storage/rqshi/RaNet/moment_localization/../lib/datasets/activitynet.py", line 17, in <module>
    class ActivityNet(data.Dataset):
  File "/storage/rqshi/RaNet/moment_localization/../lib/datasets/activitynet.py", line 19, in ActivityNet
    vocab = torchtext.vocab.pretrained_aliases["glove.6B.300d"]()
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 484, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 323, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 432, in cache
    self.itos, self.stoi, self.vectors, self.dim = torch.load(path_pt)
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/storage/rqshi/anaconda3/envs/ranee/lib/python3.7/site-packages/torch/serialization.py", line 560, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: .vector_cache/glove.6B.300d.txt.pt is a zip archive (did you mean to use torch.jit.load()?)
```
which happens with pytorch<1.6 that loads models in a different way.
It seems that these two requirements are causing a conflict.

**Comment by UX404** [comment]
Using pytorch 1.1.0 raises another error:
```
Traceback (most recent call last):
  File "moment_localization/test.py", line 13, in <module>
    import datasets
  File "/RaNet/moment_localization/../lib/datasets/__init__.py", line 53, in <module>
    from datasets.activitynet import ActivityNet
  File "/RaNet/moment_localization/../lib/datasets/activitynet.py", line 17, in <module>
    class ActivityNet(data.Dataset):
  File "/RaNet/moment_localization/../lib/datasets/activitynet.py", line 19, in ActivityNet
    vocab = torchtext.vocab.pretrained_aliases["glove.6B.300d"]()
  File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 484, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 323, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 432, in cache
    self.itos, self.stoi, self.vectors, self.dim = torch.load(path_pt)
  File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torch/serialization.py", line 560, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: .vector_cache/glove.6B.300d.txt.pt is a zip archive (did you mean to use torch.jit.load()?)
```
which happens with pytorch<1.6 that loads models in a different way.
It seems that these two requirements are causing a conflict.

**Comment by Huntersxsx** [comment]
> Using pytorch 1.1.0 raises another error:
> 
> ```
> Traceback (most recent call last):
>   File "moment_localization/test.py", line 13, in <module>
>     import datasets
>   File "/RaNet/moment_localization/../lib/datasets/__init__.py", line 53, in <module>
>     from datasets.activitynet import ActivityNet
>   File "/RaNet/moment_localization/../lib/datasets/activitynet.py", line 17, in <module>
>     class ActivityNet(data.Dataset):
>   File "/RaNet/moment_localization/../lib/datasets/activitynet.py", line 19, in ActivityNet
>     vocab = torchtext.vocab.pretrained_aliases["glove.6B.300d"]()
>   File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 484, in __init__
>     super(GloVe, self).__init__(name, url=url, **kwargs)
>   File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 323, in __init__
>     self.cache(name, cache, url=url, max_vectors=max_vectors)
>   File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torchtext/vocab.py", line 432, in cache
>     self.itos, self.stoi, self.vectors, self.dim = torch.load(path_pt)
>   File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
>     return _load(f, map_location, pickle_module, **pickle_load_args)
>   File "/anaconda3/envs/ranee/lib/python3.7/site-packages/torch/serialization.py", line 560, in _load
>     raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
> RuntimeError: .vector_cache/glove.6B.300d.txt.pt is a zip archive (did you mean to use torch.jit.load()?)
> ```
> 
> which happens with pytorch<1.6 that loads models in a different way. It seems that these two requirements are causing a conflict.

We use torchtext  0.4.0 and pytorch 1.1.0 in our implementation, you can check the version of the packages
